### ISSUE TITLE
Replacement to TheoKanning?

### ISSUE THREAD

**Issue by n-saw** [Ran-Mewo/openai-java#1]
Given that upstream project https://github.com/TheoKanning/openai-java does not seem to be maintained any more, are you planning to keep this repo up-to-date with new changes and publish JAR to Maven, and if so may of us can switch to using this?

**Comment by Ran-Mewo** [comment]
I am so sorry I completely missed this issue as I don't check issues for my personal project repos

This repo was created for my personal use
I was planning to maintain it and keep this up-to-date but now I am currently moving to https://github.com/Lambdua/openai4j
I plan on making PRs in that repo to bring some of the changes I made

If Lambdua decides to not merge some of my important changes or if they stops maintaining it then I'll create a fork of that and maintain it
